### ISSUE TITLE
publish a UMD build

### ISSUE THREAD

**Issue by ryepup** [demipixel/factorio-blueprint#28]
I'm interested in using factorio-blueprint in the browser via [unpkg][] and a `<script>` element. [unpkg][] require a UMD build; some kind of .min.js file that has all the code and dependencies bundled together.

Currently unpkg will serve the index.js, which will not work in browsers due to `require` usage.

This is also coming out of camerongillette/factorio_blueprint_editor#16

[unpkg]: https://unpkg.com/

**Comment by r04r** [comment]
browserify?

**Comment by demipixel** [comment]
Yup, browserify works great.

Here's what autotorio does:
https://github.com/demipixel/autotorio/blob/master/scripts/postinstall.js

Notice how I have to replace zlib with "browserify-zlib-next". This is because the original browserify-zlib caused crashes at the time. I believe this no longer happens (I just haven't changed it in autotorio). If it does still occur, you'll need to use the [custom browserify-zlib-next](https://github.com/demipixel/autotorio/blob/master/package.json#L14) library I made to have it all work :)

**Comment by ryepup** [comment]
Agreed, the consumer could use browserify or webpack to make their own bundles.

Right now the codebase I'm thinking of has no build process whatsoever, and only runs in the browser.  The unpkg service is a really beginner-friendly option, and I was exploring how far you could in 2017 without a build process. Maybe that effort is better spent working through webpack config?

**Comment by demipixel** [comment]
One option is to save the build process on the repo as well as the compiled file. This means people who pull/clone it won't have to build to use it (and to update it, you just run the build command again and push).

**Comment by ryepup** [comment]
@demipixel I think I got the correct config to generate the bundle sorted in the consuming project, figured I'd drop it in here too in case you want it. If not, feel free to close out this issue and the PR.
